### ISSUE TITLE
Testing with Cleaner Version

### ISSUE THREAD

**Issue by Yocodeyo** [ShuyangCao/cliff_summ#15]
Hi, thank you for this interesting and inspiring work!
I tried to replicate your implementation by referring to the cleaner [version](https://github.com/ShuyangCao/cliff_summ/tree/main/new_fairseq_implementation) of implementation. It can train the model successfully and obtain checkpoint.py file. However, in the documentation for cleaner version it did not describe preprocessing step for test data so I’m not very sure how to fairseq-generate after getting the checkpoint.pt file. May I get your advice on that? Thank you very much!:)

**Comment by ShuyangCao** [comment]
You can follow the original implementation for the data preprocessing of the test dataset (or you can follow the fairseq BART [document](https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.summarization.md)). The new implementation is only for training the model.
