### ISSUE TITLE
Question about UPDATE_FREQ

### ISSUE THREAD

**Issue by SISCHOI** [ShuyangCao/cliff_summ#9]
TOTAL_NUM_UPDATES=20000
WARMUP_UPDATES=500
LR=3e-05
MAX_TOKENS=1024
UPDATE_FREQ=32

The ReadMe from fairseq.example.bart.summarization said that the UPDATE_FREQ is 4 when you have 8 gpu.
However the code from cliff_summ said its UPDATE_FREQ=32 but it trained with 2 gpu.
Could you tall me about why the parameter isnot UPDATE_FREQ=16 with 2gpu? Is it about the CL？
Thanks .

**Comment by ShuyangCao** [comment]
Our `MAX_TOKENS` is half of the original bart script. `UPDATE_FREQ=32` is used to ensure we have the same value of `MAX_TOKENS x UPDATE_FREQ x NUM_GPUS`

**Comment by SISCHOI** [comment]
Thanks very much for your answer
